#!/bin/bash

## Description: Installs DrupalX and opens it in a browser.

ddev start
ddev composer install
ddev . drush webform-libraries-download
ddev . drush si -y --verbose drupalx
open $DDEV_PRIMARY_URL
