#!/bin/bash

## Description: Installs DrupalX and opens it in a browser.

ddev start
ddev composer install
ddev drush site:install minimal --verbose -y
ddev drush recipe ../recipes/drupalx-core
ddev drush recipe ../recipes/drupalx-standard
ddev drush cr

ddev drush scr ../scripts/install-cleanup.php
ddev drush uli
