#!/bin/bash

## Description: Installs DrupalX and opens it in a browser.

ddev start
ddev composer install
ddev drush site:install minimal --verbose -y
ddev drush recipe -v ../recipes/drupalx-recipe
ddev drush uli
