# This file MUST be named `recipe.yml`.

# Change this as you see fit.
name: Blank

# A short description that will be visible in the Drupal CMS installer.
description: 'A blank template with the foundational features of Drupal CMS, for those who truly want to start from scratch.'

# All site templates must have the `Site` type (case-sensitive); don't change this.
type: Site

# Recipes to apply before this one. None of these should be site templates
# themselves; a site template can be built on any number of smaller recipes,
# but you shouldn't build a site template on top of another site template
# (or combination of site templates).
recipes:
  #
  # ### Recommended recipes from Drupal core:
  #
  # Defines a generic administrator role, with all permissions.
  - core/recipes/administrator_role
  # Installs recommended core modules to help with site maintenance.
  - core/recipes/core_recommended_maintenance
  # Installs recommended core modules to boost Drupal's performance.
  - core/recipes/core_recommended_performance
  #
  # ### Recommended recipes from Drupal CMS:
  #
  # Sets up the administrative backend, with a nice theme and useful modules
  # providing helpful site management functionality.
  - drupal_cms_admin_ui
  # Basic anti-spam protection.
  - drupal_cms_anti_spam
  # Useful tweaks to user authentication.
  - drupal_cms_authentication
  # A set of basic media types and configuration.
  - drupal_cms_media
  # Basic privacy and consent management tools.
  - drupal_cms_privacy_basic
  # Basic SEO tools and configuration.
  - drupal_cms_seo_basic
  # Configures Drupal to send nice-looking HTML emails.
  - easy_email_express

# A list of modules and themes to install.
install:
  # Provides useful tools for site template creators, and polyfills functionality that is not yet in Drupal core.
  - drupal_cms_helper
  # By default, Drupal installs Stark as the default theme. It must be listed here, at
  # least initially, to prevent bugs if it's not present. You can remove it later if you
  # want to; just uninstall it before exporting the site as a recipe.
  - stark
  # A blank theme, generated by drupal/site_template_helper (see composer.json).
  - blank

config:
  # Ensures that this recipe will not conflict with any existing configuration. In
  # other words, if this recipe supplies configuration that a site already has, the
  # existing configuration will "win" and be left alone. Don't change this unless you
  # know what you're doing; most site templates provide configuration that will break
  # at install time if you change this.
  strict: false

  actions:
    # Set the home page to a blank Canvas landing page.
    system.site:
      simpleConfigUpdate:
        page.front: '/home'
    # By default, use the blank theme generated by the site template helper plugin.
    # @see `composer.json`
    system.theme:
      simpleConfigUpdate:
        default: 'blank'
    # Disable Canvas components that aren't really useful in building pages or
    # content templates. This doesn't delete the components; it only prevents
    # them from appearing in the Canvas UI. If you want any of these components
    # to be enabled by default, delete them from this list.
    ?canvas.component.block.announce_block:
      disable: []
    ?canvas.component.block.dashboard_placeholder:
      disable: []
    ?canvas.component.block.dashboard_site_status:
      disable: []
    canvas.component.block.local_actions_block:
      disable: []
    canvas.component.block.local_tasks_block:
      disable: []
    ?canvas.component.block.navigation_dashboard:
      disable: []
    ?canvas.component.block.navigation_link:
      disable: []
    ?canvas.component.block.navigation_shortcuts:
      disable: []
    ?canvas.component.block.navigation_user:
      disable: []
    canvas.component.block.project_browser_block.*:
      disable: []
    ?canvas.component.block.system_menu_block.admin:
      disable: []
    ?canvas.component.block.system_menu_block.navigation-user-links:
      disable: []
    ?canvas.component.block.system_menu_block.tools:
      disable: []
    ?canvas.component.block.system_menu_block.top-tasks:
      disable: []
    canvas.component.block.system_messages_block:
      disable: []
    ?canvas.component.block.views_block.publishing_content-block_drafts:
      disable: []
    ?canvas.component.block.views_block.publishing_content-block_scheduled:
      disable: []
    ?canvas.component.block.views_block.recent_pages-block_recent_pages:
      disable: []
    ?canvas.component.sdc.navigation.title:
      disable: []
    ?canvas.component.block.events_block:
      disable: []

extra:
  recipe_installer_kit:
    # Send users to the dashboard (provided by drupal_cms_admin_ui) after installation.
    finish_url: '/admin/dashboard/welcome'
#
#  Optional information for the Drupal CMS installer (uncomment this section to enable):
#
#  drupal_cms_installer:
#    links:
#      # A demo of the site template, if you have one. The provided Tugboat configuration can be
#      # used to set this up, or you could generate a static HTML version of the site, or link
#      # to a demo video on YouTube, etc.
#      - url: 'https://www.example.com/my-site-template/demo'
#        text: Demo
#      # The site template's project page, marketplace listing, or dedicated website, if any.
#      - url: 'https://www.example.com/my-site-template'
#        text: Learn more
