name: Run Cypress Tests

on:
  push:
    branches:
      - 10.x
  pull_request:
    branches:
      - 10.x

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Install NPM dependencies
        run: npm install
        working-directory: ./web/themes/contrib/drupalx_theme

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1280x1024x24 &
        env:
          DISPLAY: :99.0

      - name: Start Storybook
        run: npm run storybook &
        working-directory: ./web/themes/contrib/drupalx_theme
        env:
          DISPLAY: :99.0

      - name: Wait for Storybook to be ready
        run: npx wait-on --timeout http://localhost:6006

      - name: Run Cypress tests
        run: npm run cypress
        working-directory: ./web/themes/contrib/drupalx_theme
        env:
          DISPLAY: :99.0
