/**
 * generate-logo.mjs — write logo.svg as a DERIVED monogram tile.
 *
 * WHY THIS EXISTS. Brand assets are the one class of file a build cannot
 * check: nothing throws when the header shows another company's mark, it just
 * ships, and it is the first thing anyone sees. The Astro twins shipped Simple
 * Spark's own bolt as the favicon of every pilot for months for exactly this
 * reason — a DRAWN mark is an identity, and an identity survives a fork
 * silently. A MONOGRAM is a function of the site name, so it cannot be
 * inherited wrongly.
 *
 * This theme had the milder version of the same bug: logo.svg was a
 * hand-drawn DrupalX mark with the old DrupalX blue (#1e4a86) baked in, so
 * when the palette moved to the shared teal-navy (2026-08-09) the mark went
 * off-brand and nothing said so.
 *
 *   npm run gen:logo                                  # "X" on the brand ink
 *   PUBLIC_SITE_NAME="Ashgrove Historical Society" npm run gen:logo
 *
 * Overrides:
 *   PUBLIC_SITE_NAME  the site name the monogram derives from
 *   LOGO_MONO         monogram letter  (default: first letter of the name)
 *   LOGO_INK          tile fill        (default: --color-primary-800)
 *   LOGO_MARK         keyline accent   (default: --color-accent-500)
 *
 * Reads the ink/accent defaults FROM src/css/global.css so the mark cannot
 * drift from the palette again. Per engagement you REPLACE logo.svg with the
 * issuer's real mark — a supplied SVG always wins; this is only for the gap
 * before one exists.
 *
 * No headless browser here (unlike the Astro twins' version, which renders a
 * PNG wordmark): this theme's mark is a 40x40 rounded tile in the header, so
 * an SVG the script can write directly is the whole job.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Pull a token's value out of the theme stylesheet — one source of truth. */
function token(name, fallback) {
  try {
    const css = readFileSync(join(root, 'src/css/global.css'), 'utf8');
    const m = css.match(new RegExp(`--${name}:\\s*([^;]+);`));
    return m ? m[1].trim() : fallback;
  } catch {
    return fallback;
  }
}

// Placeholder names must never be letterpressed into a mark. The Astro twins
// filter their loud "Set PUBLIC_SITE_NAME in .env" sentinel here; this stack's
// equivalent is the starter's own product name.
const PLACEHOLDERS = [/^Set /, /^DrupalX/i];
const real = (v) => (v && !PLACEHOLDERS.some((re) => re.test(v)) ? v : null);

const REAL_NAME = real(process.env.PUBLIC_SITE_NAME);
const NAME = REAL_NAME ?? 'Your Organization';
// The monogram derives from a REAL site name. With only the placeholder, the
// starter shows the DrupalX "X" — never the "Y" of "Your Organization", which
// reads as a mistake rather than a placeholder.
const MONO = (process.env.LOGO_MONO ?? (REAL_NAME ? REAL_NAME.trim()[0] : 'X')).toUpperCase();
const INK = process.env.LOGO_INK ?? token('color-primary-800', '#002d40');
const MARK = process.env.LOGO_MARK ?? token('color-accent-500', '#00a596');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48" height="48" role="img" aria-label="${NAME}">
  <!-- GENERATED by scripts/generate-logo.mjs (npm run gen:logo).
       A monogram DERIVED from PUBLIC_SITE_NAME, not a drawn mark: a drawn
       mark is an identity and survives a fork silently, wrong one generation
       later. Ink + keyline come from src/css/global.css, so a recolor cannot
       leave this behind.
       PER ENGAGEMENT: replace with the ISSUER's real logo. -->
  <rect width="48" height="48" rx="12" fill="${INK}"/>
  <text x="24" y="24" text-anchor="middle" dominant-baseline="central"
        font-family="Fraunces, Georgia, 'Times New Roman', serif"
        font-size="26" font-weight="700" fill="#ffffff">${MONO}</text>
  <rect x="14" y="35" width="20" height="3" rx="1.5" fill="${MARK}"/>
</svg>
`;

const out = join(root, 'logo.svg');
writeFileSync(out, svg);
console.log(`generate-logo: wrote ${out.replace(root + '/', '')}`);
console.log(`  name "${NAME}"  monogram "${MONO}"`);
console.log(`  ink ${INK}  mark ${MARK}  (from src/css/global.css)`);
